---
osdeps_mode: os,gem,pip
reused_autoproj_installations: []
GITORIOUS: git
GITORIOUS_ROOT: git://gitorious.org
GITORIOUS_PUSH_ROOT: ! 'git@gitorious.org:'
GITHUB: http
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: ! 'git@github.com:'
ROCK_FLAVOR: @ROCK_FLAVOR@
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb
autoproj_use_prerelease: false
